name: Publish to GitHub Pages

on:
  push:
    branches:
      - master 

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.126.2
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Hugo build
        run: |
          export HUGOxPARAMSxGITxLAST_COMMITxHASH=$(git rev-parse --short HEAD)
          export HUGOxPARAMSxGITxLAST_COMMITxDATE=$(git log -1 --format=%ci | cut -b 1-10)
          url=$(curl https://api.github.com/repos/jherzstein/jordanherzstein.com | jq '.homepage')
          hugo --baseURL $url
      - name: Publish generated content to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: public
